clasificacion_choices = (
    ('critico','Critico'),
    ('mayor','Mayor'),
     ('critico','Critico'),
    ('menor','Menor'),
     ('critico','Critico'),
    ('informativo','Informativo'),
)




tipoAccion_choices = (
    ('mejora','MEJORA'),
    ('correctiva','CORRECTIVA'),
   
)


fuentePlan_choices = (
    ('AUDITORÍA INTERNA','AUDITORÍA INTERNA'),
    ('AUDITORIA O VISITA EXTERNA','AUDITORIA O VISITA EXTERNA'),
     ('PAMEC ','PAMEC '),
    ('SEGUIMIENTO AL PROCESO','SEGUIMIENTO AL PROCESO'),
     ('ATENCIÓN A QUEJA,  RECLAMACIÓN O SUGERENCIA DEL  CLIENTE ','ATENCIÓN A QUEJA,  RECLAMACIÓN O SUGERENCIA DEL  CLIENTE '),
    ('SALIDAS NO CONFORMES ','SALIDAS NO CONFORMES '),
     ('REQUISITOS LEGALES /HABILITACIÓN  ','REQUISITOS LEGALES /HABILITACIÓN '),
)



proceso_choices = (
    ('PLANEACIÓN ESTRATÉGICA', 'PLANEACIÓN ESTRATÉGICA'),
    ('GESTIÓN DE PROYECTOS', 'GESTIÓN DE PROYECTOS'),
     ('GESTIÓN DE LA INVESTIGACIÓN', 'GESTIÓN DE LA INVESTIGACIÓN '),
    ('SERVICIOS DE SALUD', 'SERVICIOS DE SALUD'),
     ('SERVICIOS AGRICOLAS ESPECIALIZADOS', 'SERVICIOS AGRICOLAS ESPECIALIZADOS'),
    ('FONDO EDITORIAL', 'FONDO EDITORIAL'),
     ('COMPRAS', 'COMPRAS'),
     ('GESTIÓN HUMANA', 'GESTIÓN HUMANA'),
    ('COMUNICACIONES Y MERCADEO', 'COMUNICACIONES Y MERCADEO'),
     ('INFRAESTRUCTURA Y SERVICIOS GENERALES ', 'INFRAESTRUCTURA Y SERVICIOS GENERALES '),
    ('GESTIÓN FINANCIERA', 'GESTIÓN FINANCIERA'),
     ('GESTIÓN DOCUMENTAL','GESTIÓN DOCUMENTAL' ),
     )
   
